### ISSUE TITLE
Make Google-Analytics EU-friendly

### ISSUE THREAD

**Issue by fmarier** [dmarti/trans-europa-express#3]
Some ideas:

- Enable [‘anonymizeelp’ setting](https://support.google.com/analytics/answer/2763052?hl=en&ref_topic=2919631)
- Disable [‘displayFeaturesTask’ setting](https://support.google.com/analytics/answer/2444872?hl=en)

**Comment by dmarti** [comment]
The above change does not seem to be working yet.

Need to figure out how to run the content script _after_ "ga" is created but _before_ it can send data.
